service: lambda-boot

plugins:
  - serverless-plugin-warmup

custom:
  warmup:
    timeout: 20
    prewarm: true
  main_class: com.lambda.boot.BootApplication
  basePath: lambda-boot

provider:
  name: aws
  runtime: java11
  memorySize: 1512
  timeout: 900
  region: eu-central-1
  stage: v1
  profile: ${opt:profile, "default"}
  endpointType: REGIONAL

package:
  individually: true

functions:
  lambda-boot-function:
    package:
      artifact: target/boot-0.0.1-SNAPSHOT-lambda-package.zip
    handler: com.lambda.boot.StreamLambdaHandler
    events:
      - websocket: $connect
      - http:
          path: /chat
          method: ANY
          cors: true
      - http:
          path: /login
          method: ANY
          cors: true
